apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sabota
  labels:
    app: sabota
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabota
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sabota
        version: v5
    spec:
      containers:
      - name: sabota
        image: *
        env:
        - name: SLACK_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: SLACK_API_TOKEN
              name: sabota
        - name: aws_access_key_id
          valueFrom:
            secretKeyRef:
              key: aws_access_key_id
              name: sabota
        - name: aws_secret_access_key
          valueFrom:
            secretKeyRef:
              key: aws_secret_access_key
              name: sabota
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 25Mi
